name: Haskell CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: 'set up HLint'
      uses: rwe/actions-hlint-setup@v1.0.2
    - name: 'run HLint'
      uses: rwe/actions-hlint-run@v2.0.1
      with:
        path: src/
        fail-on: error
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: 'compile'
      run: stack build --test --no-run-tests